      PROGRAM TIME_ORGQR_K
      INTEGER     M, N, K, LWORK, INFO, NEG_ONE
      REAL START, FINISH
      DOUBLE PRECISION  ZERO

      DOUBLE PRECISION, ALLOCATABLE :: V(:,:), Q(:,:),
     $   WORK(:), TAU(:)

      DOUBLE PRECISION, DIMENSION(6) :: TIMEVEC, PERFVEC

      INTRINSIC CPU_TIME

      NEG_ONE = -1
      ZERO = 0.0D+0

      WRITE(*,*) "Provide M,N,K for ORGQR"
      READ(*,*) M, N, K

      ALLOCATE(V(M,K))
      ALLOCATE(Q(M,N))
      ALLOCATE(TAU(K))
      ALLOCATE(WORK(1))

      CALL RANDOM_NUMBER(V)
      CALL RANDOM_NUMBER(TAU)

      CALL DORGQR(M, N, K, Q, M, TAU, WORK, NEG_ONE, INFO)
      LWORK = INT(WORK(1))
      CALL DORGQR_REF_K(M, N, K, Q, M, TAU, WORK, NEG_ONE, INFO)
      LWORK = MAX(INT(WORK(1)),LWORK)
      CALL DGEQRF(M, K, V, M, TAU, WORK, NEG_ONE, INFO)
      LWORK = MAX(INT(WORK(1)),LWORK)

      DEALLOCATE(WORK)
      ALLOCATE(WORK(LWORK))

      CALL DGEQRF(M, K, V, M, TAU, WORK, LWORK, INFO)
      CALL DLASET('All', M, N, ZERO, ZERO, Q, M)
      CALL DLACPY('All', M, K, V, M, Q, M)
      !
      CALL CPU_TIME(START)

      CALL DORGQR(M, N, K, Q, M, TAU, WORK, LWORK, INFO)

      CALL CPU_TIME(FINISH)
      TIMEVEC(1) = FINISH - START
      CALL CPU_TIME(START)

      CALL DORGQR_REF_K(M, N, K, Q, M, TAU, WORK, LWORK, INFO)

      CALL CPU_TIME(FINISH)
      TIMEVEC(2) = FINISH - START

      CALL CPU_TIME(START)

      CALL DORGQR_LVL2_K(M, N, K, Q, M, TAU, WORK, LWORK, INFO)

      CALL CPU_TIME(FINISH)
      TIMEVEC(3) = FINISH - START

      CALL CPU_TIME(START)

      CALL DORGQR_REC_K(M, N, K, Q, M, TAU, WORK, LWORK, INFO)

      CALL CPU_TIME(FINISH)
      TIMEVEC(4) = FINISH - START

      CALL CPU_TIME(START)

      CALL DORGQR_UT_INV_K(M, N, K, Q, M, TAU, WORK, LWORK, INFO)

      CALL CPU_TIME(FINISH)
      TIMEVEC(5) = FINISH - START
      CALL CPU_TIME(START)

      CALL DORGQR_UT_SOLVE_K(M, N, K, Q, M, TAU, WORK, LWORK, INFO)

      CALL CPU_TIME(FINISH)
      TIMEVEC(6) = FINISH - START

      CALL QX_PERF(TIMEVEC,PERFVEC,M,N,K)
      WRITE(*,*) "QR_TIME:", TIMEVEC
      WRITE(*,*) "QR_PERF:", PERFVEC
      DEALLOCATE(V)
      DEALLOCATE(Q)
      DEALLOCATE(TAU)
      DEALLOCATE(WORK)

      ALLOCATE(V(K,M))
      ALLOCATE(Q(N,M))
      ALLOCATE(TAU(K))
      ALLOCATE(WORK(1))

      CALL RANDOM_NUMBER(V)
      CALL RANDOM_NUMBER(TAU)

      CALL DORGLQ(N, M, K, Q, N, TAU, WORK, NEG_ONE, INFO)
      LWORK = INT(WORK(1))
      CALL DORGLQ_REF_K(N, M, K, Q, N, TAU, WORK, NEG_ONE, INFO)
      LWORK = MAX(INT(WORK(1)),LWORK)
      CALL DGELQF(K, M, V, K, TAU, WORK, NEG_ONE, INFO)
      LWORK = MAX(INT(WORK(1)),LWORK)

      DEALLOCATE(WORK)
      ALLOCATE(WORK(LWORK))

      CALL DGELQF(K, M, V, K, TAU, WORK, LWORK, INFO)
      CALL DLASET('All', N, M, ZERO, ZERO, Q, N)
      CALL DLACPY('All', K, M, V, K, Q, N)
      !
      CALL CPU_TIME(START)

      CALL DORGLQ(N, M, K, Q, N, TAU, WORK, LWORK, INFO)

      CALL CPU_TIME(FINISH)
      TIMEVEC(1) = FINISH - START
      CALL CPU_TIME(START)

      CALL DORGLQ_REF_K(N, M, K, Q, N, TAU, WORK, LWORK, INFO)

      CALL CPU_TIME(FINISH)
      TIMEVEC(2) = FINISH - START

      CALL CPU_TIME(START)

      CALL DORGLQ_LVL2_K(N, M, K, Q, N, TAU, WORK, LWORK, INFO)

      CALL CPU_TIME(FINISH)
      TIMEVEC(3) = FINISH - START

      CALL CPU_TIME(START)

      CALL DORGLQ_REC_K(N, M, K, Q, N, TAU, WORK, LWORK, INFO)

      CALL CPU_TIME(FINISH)
      TIMEVEC(4) = FINISH - START

      CALL CPU_TIME(START)

      CALL DORGLQ_UT_INV_K(N, M, K, Q, N, TAU, WORK, LWORK, INFO)

      CALL CPU_TIME(FINISH)
      TIMEVEC(5) = FINISH - START
      CALL CPU_TIME(START)

      CALL DORGLQ_UT_SOLVE_K(N, M, K, Q, N, TAU, WORK, LWORK, INFO)

      CALL CPU_TIME(FINISH)
      TIMEVEC(6) = FINISH - START

      CALL XQ_PERF(TIMEVEC,PERFVEC, N, M, K)
      WRITE(*,*) "LQ_TIME:",TIMEVEC
      WRITE(*,*) "LQ_PERF:",PERFVEC
10    DEALLOCATE(V)
      DEALLOCATE(Q)
      DEALLOCATE(TAU)
      DEALLOCATE(WORK)
      END PROGRAM

      SUBROUTINE QX_PERF(QXTIMES, QXPERF, M, N, K)
         DOUBLE PRECISION, DIMENSION(6) :: QXTIMES,QXPERF
         INTEGER M,N,K
         DOUBLE PRECISION TMP, TIME, TWO, THREE, FOUR
         PARAMETER(TIME=1.0D+9, TWO=2.0D+0, THREE=3.0D+0, FOUR=4.0D+0)
         DOUBLE PRECISION A,B,C
         A = DBLE(M)
         B = DBLE(N)
         C = DBLE(K)
         TMP = FOUR*A*B*C - TWO*(A+B)*C*C + FOUR/THREE*C*C*C + THREE*B*C
     $          - A*C - C*C - FOUR/THREE*C
         QXPERF(1:6) = TMP / (QXTIMES(1:6)*TIME)
      END SUBROUTINE

      SUBROUTINE XQ_PERF(XQTIMES, XQPERF, M, N, K)
         DOUBLE PRECISION, DIMENSION(6) :: XQTIMES,XQPERF
         INTEGER M,N,K
         DOUBLE PRECISION TMP, TIME, TWO, THREE, FOUR
         PARAMETER(TIME=1.0D+9, TWO=2.0D+0, THREE=3.0D+0, FOUR=4.0D+0)
         DOUBLE PRECISION A,B,C
         A = DBLE(M)
         B = DBLE(N)
         C = DBLE(K)
         TMP = FOUR*A*B*C - TWO*(A+B)*C*C + FOUR/THREE*C*C*C
     $          + TWO*A*C - C*C - C/THREE
         XQPERF(1:6) = TMP / (XQTIMES(1:6)*TIME)
      END SUBROUTINE
